// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA58prE6JG4-M3m-sUrL2wuoSTdd-Tyl5U',
    appId: '1:497550426554:web:bafbe89b90cda5f326dd83',
    messagingSenderId: '497550426554',
    projectId: 'private-chats-d404c',
    authDomain: 'private-chats-d404c.firebaseapp.com',
    storageBucket: 'private-chats-d404c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN1i0U2tug5YlVATwPG5Hes9QUbpVSXDI',
    appId: '1:497550426554:android:105b1b987f48d7ea26dd83',
    messagingSenderId: '497550426554',
    projectId: 'private-chats-d404c',
    storageBucket: 'private-chats-d404c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfsfa9dE7ykqmTXKeymPgjZc1THeVb5Ks',
    appId: '1:497550426554:ios:2fee1388e1020ca226dd83',
    messagingSenderId: '497550426554',
    projectId: 'private-chats-d404c',
    storageBucket: 'private-chats-d404c.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );
}
